CREATE DATABASE bdCads;
USE bdCads;
/*TABELA DE PRODUTOS*/
CREATE TABLE tbProduto (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    VALOR DECIMAL(10, 2) NOT NULL,
    DESCRICAO VARCHAR(255) NOT NULL,
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
/*TABELA DE CADASTRO*/
CREATE TABLE tbCadastro (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    SENHA VARCHAR(100) NOT NULL UNIQUE,
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
/*TABELA DE USUÁRIOS*/
CREATE TABLE tbUsuario (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    SENHA VARCHAR(100) NOT NULL UNIQUE,
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ID_CADASTRO INT,
    FOREIGN KEY (ID_CADASTRO) REFERENCES tbCadastro(ID)
);
/*TABELA DE ADMINISTRADORES*/
CREATE TABLE tbAdmin (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    SENHA VARCHAR(100) NOT NULL UNIQUE,
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ID_CADASTRO INT,
    FOREIGN KEY (ID_CADASTRO) REFERENCES tbCadastro(ID)
);

/*TABELA DE CADASTRO DE PRODUTOS*/
CREATE TABLE tbCadastroProduto (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    VALOR DECIMAL(10, 2) NOT NULL,
    DESCONTO DECIMAL(5, 3) NOT NULL,
    QUANT INT,
    DESCRICAO VARCHAR(255) NOT NULL,
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ID_PRODUTO INT,
    FOREIGN KEY (ID_PRODUTO) REFERENCES tbProduto(ID)
);
/* INSERINDO DADOS NA TABELA DE PRODUTOS */
    INSERT INTO tbProduto (NOME, VALOR, DESCRICAO)
    VALUES 
    (Celular, 1500.00, 'Smartphone de última geração com câmera de alta resolução e bateria de longa duração.');
/* INSERINDO DADOS NA TABELA DE PRODUTOS */
    INSERT INTO tbProduto (NOME, VALOR, DESCRICAO)
    VALUES 
    (Celular, 1500.00, 'Smartphone de última geração com câmera de alta resolução e bateria de longa duração.');
/* INSERINDO DADOS NA TABELA DE PRODUTOS */
    INSERT INTO tbProduto (NOME, VALOR, DESCRICAO)
    VALUES 
    (Celular, 1500.00, 'Smartphone de última geração com câmera de alta resolução e bateria de longa duração.');
/* INSERINDO DADOS NA TABELA DE PRODUTOS */
    INSERT INTO tbProduto (NOME, VALOR, DESCRICAO)
    VALUES 
    (Celular, 1500.00, 'Smartphone de última geração com câmera de alta resolução e bateria de longa duração.');
/* INSERINDO DADOS NA TABELA DE PRODUTOS */
    INSERT INTO tbProduto (NOME, VALOR, DESCRICAO)
    VALUES 
    (Celular, 1500.00, 'Smartphone de última geração com câmera de alta resolução e bateria de longa duração.');