CREATE DATABASE bdCads;
Use bdCads;
/*TABELA DE PRODUTOS*/
CREATE TABLE tbProduto (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    VALOR DECIMAL(10, 2) NOT NULL,
    DESCRICAO VARCHAR(255) NOT NULL,
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
/*TABELA DE USUÁRIOS*/
CREATE TABLE tbUsuario (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    SENHA VARCHAR(100) NOT NULL UNIQUE,
    ID_CADASTROUSUARIO INT FOREIGN KEY REFERENCES tbCadastroUsuario(ID),
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
/*TABELA DE ADMINISTRADORES*/
CREATE TABLE tbAdmin (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    SENHA VARCHAR(100) NOT NULL UNIQUE,
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
/*TABELA DE CADASTRO DE USUÁRIOS*/
CREATE TABLE tbCadastroUsuario (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    SENHA VARCHAR(100) NOT NULL UNIQUE,
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
/*TABELA DE CADASTRO DE PRODUTOS*/
CREATE TABLE tbCadastroProduto (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    VALOR DECIMAL(10, 2) NOT NULL,
    DESCONTO DECIMAL(5, 3) NOT NULL,
    QUANT INT NOT NULL,
    DESCRICAO VARCHAR(255) NOT NULL,
    ID_PRODUTO INT FOREIGN KEY REFERENCES tbProduto(ID),
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);